// Generated file, do not manually edit. Generate from BE instead (php artisan app:generate-permission-constants)
export const Permissions = {
  VIEW_HORIZON_DASHBOARD: 'view_horizon_dashboard',
  VIEW_ADMIN_DASHBOARD: 'view_admin_dashboard',
  MANAGE_USERS: 'manage_users',
  BROWSE_USERS: 'browse_users',
  READ_USER: 'read_user',
  EDIT_USER: 'edit_user',
  ADD_USER: 'add_user',
  DELETE_USER: 'delete_user',
  MANAGE_SUBCATEGORIES: 'manage_subcategories',
  BROWSE_SUBCATEGORIES: 'browse_subcategories',
  READ_SUBCATEGORY: 'read_subcategory',
  EDIT_SUBCATEGORY: 'edit_subcategory',
  ADD_SUBCATEGORY: 'add_subcategory',
  DELETE_SUBCATEGORY: 'delete_subcategory',
  MANAGE_CONTENTS: 'manage_contents',
  BROWSE_CONTENTS: 'browse_contents',
  READ_CONTENT: 'read_content',
  EDIT_CONTENT: 'edit_content',
  ADD_CONTENT: 'add_content',
  DELETE_CONTENT: 'delete_content',
  MANAGE_PAYMENTS: 'manage_payments',
  BROWSE_PAYMENTS: 'browse_payments',
  READ_PAYMENT: 'read_payment',
  EDIT_PAYMENT: 'edit_payment',
  ADD_PAYMENT: 'add_payment',
  DELETE_PAYMENT: 'delete_payment',
};
